/*
(c) 2026 by Matthias Thiele
DRS 2 Stellpult
 */
package de.mmth.drs2panel.fields;

/**
 *
 * @author matthias
 */
public enum FieldType {
  SCHLUESSELWEICHE1A,
  SCHLUESSELWEICHE1B,
  SCHLUESSELWEICHE1C,
  SCHLUESSELWEICHE3A,
  SCHLUESSELWEICHE3B,
  SCHLUESSELWEICHE3C,
  SCHLUESSELWEICHE4A,
  SCHLUESSELWEICHE4B,
  TASTENKAPPEN,
  TASTENANSCHALTER_TOP,
  TASTENANSCHALTER_BOTTOM
}
